#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, symbol_short, Address, BytesN, Env,
    Symbol, Vec,
};

// Cross-contract client generated by the `product-registry` crate.
use product_registry::ProductRegistryClient;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Checkpoint {
    pub product_id: BytesN<32>,
    pub handler: Address,
    pub location: Symbol,
    pub status: Symbol,
    pub stage: u32,
    pub timestamp: u64,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Checkpoint(BytesN<32>, u32),
    CheckpointCount(BytesN<32>),
    RegistryAddress,
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    UnauthorizedHandler = 3,
    ProductNotFound = 4,
    InvalidInput = 5,
}

// ---------------------------------------------------------------------------
// Contract
// ---------------------------------------------------------------------------

#[contract]
pub struct CheckpointTracker;

#[contractimpl]
impl CheckpointTracker {
    /// One-time initialization that stores the `ProductRegistry` contract
    /// address.  Only `admin` (who must authorize) can call this.
    pub fn initialize(
        env: Env,
        admin: Address,
        registry_address: Address,
    ) -> Result<(), Error> {
        admin.require_auth();

        if env.storage().persistent().has(&DataKey::RegistryAddress) {
            return Err(Error::AlreadyInitialized);
        }

        env.storage()
            .persistent()
            .set(&DataKey::RegistryAddress, &registry_address);

        Ok(())
    }

    /// Record a supply-chain checkpoint.
    ///
    /// Performs a cross-contract call to the `ProductRegistry` to verify that
    /// `handler` is authorized for the given `product_id`.  The `stage` field
    /// auto-increments per product.  Emits a `chk_rec` event.
    pub fn record_checkpoint(
        env: Env,
        handler: Address,
        product_id: BytesN<32>,
        location: Symbol,
        status: Symbol,
    ) -> Result<(), Error> {
        handler.require_auth();

        // Retrieve registry address (must be initialized first).
        let registry_address: Address = env
            .storage()
            .persistent()
            .get(&DataKey::RegistryAddress)
            .ok_or(Error::NotInitialized)?;

        // Cross-contract call: verify handler authorization.
        let registry_client = ProductRegistryClient::new(&env, &registry_address);
        if !registry_client.is_handler(&product_id, &handler) {
            return Err(Error::UnauthorizedHandler);
        }

        // Auto-increment stage counter for this product.
        let count_key = DataKey::CheckpointCount(product_id.clone());
        let stage: u32 = env.storage().persistent().get(&count_key).unwrap_or(0);

        let checkpoint = Checkpoint {
            product_id: product_id.clone(),
            handler: handler.clone(),
            location: location.clone(),
            status: status.clone(),
            stage,
            timestamp: env.ledger().timestamp(),
        };

        let checkpoint_key = DataKey::Checkpoint(product_id.clone(), stage);
        env.storage().persistent().set(&checkpoint_key, &checkpoint);
        env.storage().persistent().set(&count_key, &(stage + 1));

        env.events().publish(
            (symbol_short!("chk_rec"), product_id),
            (handler, location, status, stage),
        );

        Ok(())
    }

    /// Return every checkpoint recorded for a product (ordered by stage).
    pub fn get_checkpoints(env: Env, product_id: BytesN<32>) -> Vec<Checkpoint> {
        let count: u32 = env
            .storage()
            .persistent()
            .get(&DataKey::CheckpointCount(product_id.clone()))
            .unwrap_or(0);

        let mut checkpoints = Vec::new(&env);
        for i in 0..count {
            let key = DataKey::Checkpoint(product_id.clone(), i);
            if let Some(cp) = env.storage().persistent().get::<DataKey, Checkpoint>(&key) {
                checkpoints.push_back(cp);
            }
        }

        checkpoints
    }

    /// Number of checkpoints recorded for a product.
    pub fn get_checkpoint_count(env: Env, product_id: BytesN<32>) -> u32 {
        env.storage()
            .persistent()
            .get(&DataKey::CheckpointCount(product_id))
            .unwrap_or(0)
    }

    /// Consumer-facing verification endpoint – returns the full checkpoint
    /// trail for a product.
    pub fn verify_product(env: Env, product_id: BytesN<32>) -> Vec<Checkpoint> {
        Self::get_checkpoints(env, product_id)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod test {
    use super::*;
    use product_registry::{ProductRegistry, ProductRegistryClient as RegistryClient};
    use soroban_sdk::testutils::Address as _;

    /// Helper: deploy both contracts, register a product, add a handler, and
    /// initialize the CheckpointTracker with the registry address.
    fn setup(env: &Env) -> (Address, Address, Address, BytesN<32>) {
        env.mock_all_auths();

        // Deploy contracts.
        let registry_id = env.register(ProductRegistry, ());
        let tracker_id = env.register(CheckpointTracker, ());

        let owner = Address::generate(env);
        let handler = Address::generate(env);
        let product_id = BytesN::from_array(env, &[1u8; 32]);

        // Set up a product with a handler in the registry.
        let registry_client = RegistryClient::new(env, &registry_id);
        registry_client.register_product(&owner, &product_id, &symbol_short!("Widget"));
        registry_client.add_handler(&owner, &product_id, &handler, &symbol_short!("shipper"));

        // Initialize tracker.
        let admin = Address::generate(env);
        let tracker_client = CheckpointTrackerClient::new(env, &tracker_id);
        tracker_client.initialize(&admin, &registry_id);

        (tracker_id, handler, owner, product_id)
    }

    #[test]
    fn test_initialize_and_record_checkpoint() {
        let env = Env::default();
        let (tracker_id, handler, _owner, product_id) = setup(&env);
        let client = CheckpointTrackerClient::new(&env, &tracker_id);

        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("NYC"),
            &symbol_short!("received"),
        );

        let checkpoints = client.get_checkpoints(&product_id);
        assert_eq!(checkpoints.len(), 1);

        let cp = checkpoints.get(0).unwrap();
        assert_eq!(cp.handler, handler);
        assert_eq!(cp.stage, 0);
        assert_eq!(cp.location, symbol_short!("NYC"));
        assert_eq!(cp.status, symbol_short!("received"));
    }

    #[test]
    fn test_sequential_checkpoints() {
        let env = Env::default();
        let (tracker_id, handler, _owner, product_id) = setup(&env);
        let client = CheckpointTrackerClient::new(&env, &tracker_id);

        // Record three sequential checkpoints.
        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("NYC"),
            &symbol_short!("picked"),
        );
        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("CHI"),
            &symbol_short!("transit"),
        );
        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("LA"),
            &symbol_short!("deliver"),
        );

        let checkpoints = client.get_checkpoints(&product_id);
        assert_eq!(checkpoints.len(), 3);

        // Verify stages auto-increment.
        assert_eq!(checkpoints.get(0).unwrap().stage, 0);
        assert_eq!(checkpoints.get(1).unwrap().stage, 1);
        assert_eq!(checkpoints.get(2).unwrap().stage, 2);

        // verify_product should return the same data.
        let verified = client.verify_product(&product_id);
        assert_eq!(verified.len(), 3);
    }

    #[test]
    #[should_panic(expected = "Error(Contract, #1)")]
    fn test_uninitialized_error() {
        let env = Env::default();
        env.mock_all_auths();

        // Deploy tracker WITHOUT initializing it.
        let tracker_id = env.register(CheckpointTracker, ());
        let client = CheckpointTrackerClient::new(&env, &tracker_id);

        let handler = Address::generate(&env);
        let product_id = BytesN::from_array(&env, &[9u8; 32]);

        // Must panic because no registry address has been set.
        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("NYC"),
            &symbol_short!("fail"),
        );
    }

    #[test]
    fn test_get_checkpoint_count() {
        let env = Env::default();
        let (tracker_id, handler, _owner, product_id) = setup(&env);
        let client = CheckpointTrackerClient::new(&env, &tracker_id);

        assert_eq!(client.get_checkpoint_count(&product_id), 0);

        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("SEA"),
            &symbol_short!("loaded"),
        );
        assert_eq!(client.get_checkpoint_count(&product_id), 1);

        client.record_checkpoint(
            &handler,
            &product_id,
            &symbol_short!("PDX"),
            &symbol_short!("transit"),
        );
        assert_eq!(client.get_checkpoint_count(&product_id), 2);
    }
}
